/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Caio
 */
public class JFrmPtePrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrmPtePrincipal.class.getName());

    /**
     * Creates new form JFrmPtePrincipal
     */
    public JFrmPtePrincipal() {
        initComponents();
        setTitle("Sistema De Jogos");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuCadastros = new javax.swing.JMenu();
        jMniUsuarios = new javax.swing.JMenuItem();
        jMniClientes = new javax.swing.JMenuItem();
        jMniFornecedores = new javax.swing.JMenuItem();
        jMniJogos = new javax.swing.JMenuItem();
        jMniAdministradoes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMniSair = new javax.swing.JMenuItem();
        jMnuMovimentos = new javax.swing.JMenu();
        jMniVendas = new javax.swing.JMenuItem();
        jMniVendasItens = new javax.swing.JMenuItem();
        jMniCompras = new javax.swing.JMenuItem();
        jMniItensCompra = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMniSairM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuCadastros.setText("Cadastros");

        jMniUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMniUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMniUsuarios.setText("Usuários");
        jMniUsuarios.addActionListener(this::jMniUsuariosActionPerformed);
        jMnuCadastros.add(jMniUsuarios);

        jMniClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMniClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMniClientes.setText("Clientes");
        jMniClientes.addActionListener(this::jMniClientesActionPerformed);
        jMnuCadastros.add(jMniClientes);

        jMniFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMniFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.png"))); // NOI18N
        jMniFornecedores.setText("Fornecedores");
        jMniFornecedores.addActionListener(this::jMniFornecedoresActionPerformed);
        jMnuCadastros.add(jMniFornecedores);

        jMniJogos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMniJogos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/jogos.png"))); // NOI18N
        jMniJogos.setText("Jogos");
        jMniJogos.addActionListener(this::jMniJogosActionPerformed);
        jMnuCadastros.add(jMniJogos);

        jMniAdministradoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMniAdministradoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/admin.png"))); // NOI18N
        jMniAdministradoes.setText("Administradores");
        jMniAdministradoes.addActionListener(this::jMniAdministradoesActionPerformed);
        jMnuCadastros.add(jMniAdministradoes);
        jMnuCadastros.add(jSeparator1);

        jMniSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMniSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMniSair.setText("Sair");
        jMniSair.addActionListener(this::jMniSairActionPerformed);
        jMnuCadastros.add(jMniSair);

        jMenuBar1.add(jMnuCadastros);

        jMnuMovimentos.setText("Movimentos");

        jMniVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jMniVendas.setText("Vendas");
        jMnuMovimentos.add(jMniVendas);

        jMniVendasItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas_itens.png"))); // NOI18N
        jMniVendasItens.setText("Vendas Intens");
        jMnuMovimentos.add(jMniVendasItens);

        jMniCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compras.png"))); // NOI18N
        jMniCompras.setText("Compras");
        jMnuMovimentos.add(jMniCompras);

        jMniItensCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/itens_compra.png"))); // NOI18N
        jMniItensCompra.setText("Itens Compra");
        jMnuMovimentos.add(jMniItensCompra);
        jMnuMovimentos.add(jSeparator2);

        jMniSairM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMniSairM.setText("Sair");
        jMniSairM.addActionListener(this::jMniSairMActionPerformed);
        jMnuMovimentos.add(jMniSairM);

        jMenuBar1.add(jMnuMovimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMniUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgPteUsuarios jDlgPteUsuarios = new JDlgPteUsuarios(null, true);
        jDlgPteUsuarios.setVisible(true);
    }//GEN-LAST:event_jMniUsuariosActionPerformed

    private void jMniClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniClientesActionPerformed
        // TODO add your handling code here:
        JDlgPteClientes jDlgPteClientes = new JDlgPteClientes(null, true);
        jDlgPteClientes.setVisible(true);
    }//GEN-LAST:event_jMniClientesActionPerformed

    private void jMniFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniFornecedoresActionPerformed
        // TODO add your handling code here:
        JDLgPteFornecedores jDLgPteFornecedores = new JDLgPteFornecedores(null, true);
        jDLgPteFornecedores.setVisible(true);
    }//GEN-LAST:event_jMniFornecedoresActionPerformed

    private void jMniJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniJogosActionPerformed
        // TODO add your handling code here:
        JDLgPteJogos jDLgPteJogos = new JDLgPteJogos(null, true);
        jDLgPteJogos.setVisible(true);
    }//GEN-LAST:event_jMniJogosActionPerformed

    private void jMniAdministradoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniAdministradoesActionPerformed
        // TODO add your handling code here:
        JDLgPteAdministradores jDLgPteAdministradores = new JDLgPteAdministradores(null, true);
        jDLgPteAdministradores.setVisible(true);
    }//GEN-LAST:event_jMniAdministradoesActionPerformed

    private void jMniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMniSairActionPerformed

    private void jMniSairMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniSairMActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMniSairMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrmPtePrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMniAdministradoes;
    private javax.swing.JMenuItem jMniClientes;
    private javax.swing.JMenuItem jMniCompras;
    private javax.swing.JMenuItem jMniFornecedores;
    private javax.swing.JMenuItem jMniItensCompra;
    private javax.swing.JMenuItem jMniJogos;
    private javax.swing.JMenuItem jMniSair;
    private javax.swing.JMenuItem jMniSairM;
    private javax.swing.JMenuItem jMniUsuarios;
    private javax.swing.JMenuItem jMniVendas;
    private javax.swing.JMenuItem jMniVendasItens;
    private javax.swing.JMenu jMnuCadastros;
    private javax.swing.JMenu jMnuMovimentos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
